[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science", "no-std", "embedded", "wasm"]
description = "Flexible and Comprehensive Deep Learning Framework in Rust"
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "tensor", "pytorch", "ndarray"]
license.workspace = true
name = "burn"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn"
version.workspace = true
rust-version = "1.75"

[features]
default = ["burn-core/default"]
std = ["burn-core/std"]
doc = ["default", "burn-core/doc", "burn-train/doc"]

# Training with full features
train = ["burn-train", "autodiff", "dataset"]

## Includes the Text UI (progress bars, metric plots)
tui = ["burn-train?/tui"]

##  Includes system info metrics (CPU/GPU usage, etc)
metrics = ["burn-train?/metrics"]

# Useful when targeting WASM and not using WGPU.
wasm-sync = ["burn-core/wasm-sync"]

# Datasets
dataset = ["burn-core/dataset"]

sqlite = ["burn-core/sqlite"]
sqlite-bundled = ["burn-core/sqlite-bundled"]

vision = ["burn-core/vision"]

# Backends
autodiff = ["burn-core/autodiff"]
fusion = ["burn-core/fusion"]

## Backend features
cuda = ["burn-core/cuda"]
metal = ["burn-core/metal"]
accelerate = ["burn-core/accelerate"]
openblas = ["burn-core/openblas"]
openblas-system = ["burn-core/openblas-system"]
blas-netlib = ["burn-core/blas-netlib"]
autotune = ["burn-core/autotune"]
template = ["burn-core/template"]

ndarray = ["burn-core/ndarray"]
wgpu = ["burn-core/wgpu"]
tch = ["burn-core/tch"]
candle = ["burn-core/candle"]

# Network utils
network = ["burn-core/network"]

# Experimental
experimental-named-tensor = ["burn-core/experimental-named-tensor"]

# Records
record-item-custom-serde = ["burn-core/record-item-custom-serde"]

[dependencies]

# ** Please make sure all dependencies support no_std when std is disabled **

burn-core = { path = "../burn-core", version = "0.13.2", default-features = false }
burn-train = { path = "../burn-train", version = "0.13.2", optional = true, default-features = false }

[package.metadata.docs.rs]
features = ["doc"]
